name: Build & Deploy Spring app example

on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    name: Build an Deploy Spring Boot app example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run:
          mvn clean install
          mvn -B package --file pom.xml